version: '3.4'

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yaml:/otel-config.yaml
    command: ["--config", "/otel-config.yaml"]

  opentelemetrydemo:
    image: ${DOCKER_REGISTRY-}opentelemetrydemo
    depends_on:
      - otel-collector
    build:
      context: .
      dockerfile: OpenTelemetryDemo/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8080:80"