receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s

exporters:
  gomod:
    github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter v0.101.0    
  logging:
    logLevel: debug
  datadog:
    api:
      key: <YOUR_DATADOG_API_KEY>
    metrics:
      hostname: ${DD_AGENT_HOST}
      tags:
        - "service:<YOUR_SERVICE_NAME>"
  file:
    path: /var/log/otel-export/s3_export.log
    rotation:
      size_megabytes: 10
      max_backups: 5
  s3:
    region: <YOUR_AWS_REGION>
    bucket: <YOUR_S3_BUCKET_NAME>
  # config for the awsexporter package
  awss3:
    s3uploader:
        region: 'eu-central-1'
        s3_bucket: 'databucket'
        s3_prefix: 'metric'
        s3_partition: 'minute'

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, file, s3]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
